"""add moderation to posts

Revision ID: 96a0c31511ec
Revises: f51f83c80273
Create Date: 2026-03-27 13:54:10.072682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a0c31511ec'
down_revision: Union[str, None] = 'f51f83c80273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('submitted_for_review_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('posts', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('review_note', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['reviewed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'review_note')
    op.drop_column('posts', 'reviewed_at')
    op.drop_column('posts', 'reviewed_by')
    op.drop_column('posts', 'submitted_for_review_at')
    # ### end Alembic commands ###
